#
# docker-compose base file used for local development, hobby deploys, and other compose use cases.
#
# If you are looking at self-hosted deployment options check
# https://posthog.com/docs/self-host
#

services:
    db:
        image: postgres:12-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${POSTGRES_POSTHOG_USER}
            POSTGRES_DB: ${POSTGRES_POSTHOG_DB}
            POSTGRES_PASSWORD: ${POSTGRES_POSTHOG_PASSWORD}
        command: postgres -c 'max_connections=1000'

    redis:
        image: redis:6.2.7-alpine
        restart: on-failure
        command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb

    clickhouse:
        #
        # Note: please keep the default version in sync across
        #       `posthog` and the `charts-clickhouse` repos
        #
        image: ${CLICKHOUSE_SERVER_IMAGE:-clickhouse/clickhouse-server:22.3}
        restart: on-failure
    zookeeper:
        image: zookeeper:3.7.0
        restart: on-failure

    kafka:
        image: bitnami/kafka:2.8.1-debian-10-r99
        restart: on-failure
        environment:
            KAFKA_BROKER_ID: 1001
            KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: 'true'

    object_storage:
        image: minio/minio:RELEASE.2022-06-25T15-50-16Z
        restart: on-failure
        environment:
            MINIO_ROOT_USER: ${OBJECT_STORAGE_ACCESS_KEY_ID}
            MINIO_ROOT_PASSWORD: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
        entrypoint: sh
        command: -c 'mkdir -p /data/posthog && minio server --address ":19000" --console-address ":19001" /data' # create the 'posthog' bucket before starting the service

    maildev:
        image: maildev/maildev:2.0.5
        restart: on-failure
