#
# `docker-compose` file used ONLY for hobby deployments.
#
# Please take a look at https://posthog.com/docs/self-host/deploy/hobby
# for more info.
#

services:
    db:
        extends:
            file: docker-compose.base.yml
            service: db
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - ./volumes/postgres-data:/var/lib/postgresql/data
    redis:
        extends:
            file: docker-compose.base.yml
            service: redis
        ports:
            - '127.0.0.1:6379:6379'
    clickhouse:
        #
        # Note: please keep the default version in sync across
        #       `posthog` and the `charts-clickhouse` repos
        #
        image: ${CLICKHOUSE_SERVER_IMAGE:-clickhouse/clickhouse-server:22.3}
        restart: on-failure
        depends_on:
            - kafka
            - zookeeper
        ports:
            - '127.0.0.1:8123:8123'
            - '127.0.0.1:8443:8443'
            - '127.0.0.1:9000:9000'
            - '127.0.0.1:9004:9004'
        volumes:
            - ./posthog/posthog/idl:/idl
            - ./posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./volumes/clickhouse-server:/etc/clickhouse-server
            - ./volumes/clickhouse-data:/var/lib/clickhouse
    zookeeper:
        image: zookeeper:3.7.0
        restart: on-failure
        volumes:
            - ./volumes/zookeeper-datalog:/datalog
            - ./volumes/zookeeper-data:/data
            - ./volumes/zookeeper-logs:/logs
    kafka:
        image: bitnami/kafka:2.8.1-debian-10-r99
        restart: on-failure
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1001
            KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: 'true'

    worker: &worker
        image: posthog/posthog:latest-release
        command: ./bin/docker-worker-celery --with-scheduler
        restart: on-failure
        environment:
            SENTRY_DSN: 'https://public@sentry.example.com/1'
            SITE_URL: https://analytics.limesurvey.org
            DISABLE_SECURE_SSL_REDIRECT: 'true'
            IS_BEHIND_PROXY: 'true'
            DATABASE_URL: 'postgres://${POSTGRES_POSTHOG_USER}:${POSTGRES_POSTHOG_PASSWORD}@db:5432/${POSTGRES_POSTHOG_DB}'
            CLICKHOUSE_HOST: 'clickhouse'
            CLICKHOUSE_DATABASE: 'posthog'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            KAFKA_URL: 'kafka://kafka'
            REDIS_URL: 'redis://redis:6379/'
            SECRET_KEY: 138ffc6b1bb079fce13c8edb27f78cda6d4bd4325ceac439e79826f1
            PGHOST: db
            PGUSER: ${POSTGRES_POSTHOG_USER}
            PGPASSWORD: ${POSTGRES_POSTHOG_PASSWORD}
            DEPLOYMENT: hobby
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
            - object_storage
    web:
        <<: *worker
        command: /compose/start
        restart: on-failure
        volumes:
            - ./compose:/compose
    caddy:
        image: caddy:2.6.1
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - web
    plugins:
        image: posthog/posthog:latest-release
        command: ./bin/plugin-server --no-restart-loop
        restart: on-failure
        environment:
            DATABASE_URL: 'postgres://${POSTGRES_POSTHOG_USER}:${POSTGRES_POSTHOG_PASSWORD}@db:5432/${POSTGRES_POSTHOG_DB}'
            KAFKA_HOSTS: 'kafka:9092'
            REDIS_URL: 'redis://redis:6379/'
            CLICKHOUSE_HOST: 'clickhouse'
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
            - object_storage

    object_storage:
        image: minio/minio:RELEASE.2022-06-25T15-50-16Z
        restart: on-failure
        environment:
            MINIO_ROOT_USER: ${OBJECT_STORAGE_ACCESS_KEY_ID}
            MINIO_ROOT_PASSWORD: ${OBJECT_STORAGE_SECRET_ACCESS_KEY}
        entrypoint: sh
        command: -c 'mkdir -p /data/posthog && minio server --address ":19000" --console-address ":19001" /data' # create the 'posthog' bucket before starting the service
        ports:
            - '127.0.0.1:19000:9000'
        volumes:
            - ./volumes/object_storage:/data

    asyncmigrationscheck:
        <<: *worker
        command: python manage.py run_async_migrations --check
        restart: 'no'
        deploy:
            replicas: 0
        image: posthog/posthog:latest-release
        environment:
            SENTRY_DSN: 'https://public@sentry.example.com/1'
            SITE_URL: https://analytics.limesurvey.org
            SECRET_KEY: 138ffc6b1bb079fce13c8edb27f78cda6d4bd4325ceac439e79826f1

